mysql:
  driverClass: "com.mysql.jdbc.Driver"
  jdbcUrl: "jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false"
  user: "root"
  password: "root"
